### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/OpenStreamr#12]
## When will the new releases come? We are waiting.

> I'm not a contributor anymore.

**Comment by GiordanoSconti** [comment]
Hi Abhigyan, can you test the last release on Windows 64 bit? Just follow the instructions you can find in the release description. I go to sleep now, let me know if it works (mine environment is: Windows 10 Pro 64 bit). If you want to get the contributor role back, you're free to ask it anytime you want.

**Comment by AbhigyanKumar** [comment]
Yep! Downloading bro.

**Comment by AbhigyanKumar** [comment]
The software works 👍 with a small executable size.
> We succeeded.
