### ISSUE TITLE
📦Repo archive

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/OpenStreamr#13]
It has been observed that this repository has received **very few changes since the first release**. So I recommend the owner to please archive the repository. Even the _OpenSource guides_ recommend to archive repositories, not in much maintenance.

# tl;dr
>We request you to **archive the repository** as it has very few changes since the first release.

**Comment by GiordanoSconti** [comment]
You're free to fork the repository and keep the project alive. I've already merged your changes. This project is going to be archived. I do not have the time to keep it updated. Sorry guys, real life needs my attention now.
