### ISSUE TITLE
Executables

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/OpenStreamr#2]
# The public
Though this project is very good ad simple to use, common people who don't know anything about programming (NodeJS, NPM and other stuff), would ignore your project. To prevent this we must make executable and release them as soon as possible. @GiordanoSconti, sorry to say but I'm using Linux and their are not many people who use linux. So, if you could use the Windows platform, it would be great as a huge number of people use Windows as it in their day-to-day life.

> The common man just knows to download the EXE and press the install button.
> Linux is amazing, but it's share in desktop is less.

**Comment by AbhigyanKumar** [comment]
I think that, the tasks sould be as follows:

- [ ] _Release an **initial 0.1** version_ of this program.

- [ ] _Enhance the GUI_ after the release

- [ ] Then **release another version** and increase the documentation context.

- [ ] Spread it in **social media** and post on **Medium** or [DEV Community](http://www.dev.to).

**Comment by GiordanoSconti** [comment]
Do not worry about the status of the README.md and ci.yml files after the merge process. I already fixed them. We did not have anymore a safe way to realize the merge.
