### ISSUE TITLE
CI/CD Github Actions Workflow Node.js CI Bug

### ISSUE THREAD

**Issue by GiordanoSconti** [GiordanoSconti/OpenStreamr#5]
**Describe the bug**
CI/CD Github Actions " ./node_modules/electron/dist/electron ." step:
Electron terminates with sigsegv signal. There's something wrong with some libraries or configuration files that come with the Virtual Machine. With a clean installation (phisical and virtual) there's no segmentation fault with the last version of Electron.

**To Reproduce**
1. Go to './github/workflows/ci.yml'.
2. Append the "run: ./node_modules/electron/dist/electron ." step.
3. Commit.

**Expected behavior**
The Electron application should run without issues and the Virtual Machine should shut down correctly.

**Desktop (please complete the following information):**
 - OS: ubuntu-latest

**Additional context**
CI/CD Workflow: Node.js CI

**Comment by AbhigyanKumar** [comment]
Yeah, you're right. But **now everything is ✔️ ** .
