### ISSUE TITLE
Slack doesn't fit!

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/OpenStreamr#7]
# Slack is 😈
I think that [Spectrum Chat](https://spectrum.chat) is a way better solution as we cannot create public channels in Slack or convert a private channel to a public one. 

Please put your suggestions below.
> It was our mistake that we made our channel private😭 and now we regret that!

**Comment by GiordanoSconti** [comment]
Take a look at Chanty:
https://www.chanty.com/pricing.html
The free plan allow us to create public and private channels.

**Comment by AbhigyanKumar** [comment]
# We are done
Spectrum has been successfully initialized. We ditch slack. The slack channel would be disbanded within next 168 hours.
