### ISSUE TITLE
😑Bad description

### ISSUE THREAD

**Issue by AbhigyanKumar** [GiordanoSconti/OpenStreamr#8]
# Abnormal description
The description may seem simplistic to us, but its way more difficult to understand because the viewer may don't know about what destreamer or snobu is. So, then he would have to look out for destreamer which is a bigger problem.

# Client is helpless
Now the client feels that it's way better to use destreamer and kicks our ass in the hell. However, he would still have to use the command-line interface of destreamer.

**Comment by GiordanoSconti** [comment]
This project is based on destreamer, therefore we need to keep a reference to snobu's repository. I might change the body of README file. I was thinking to add images which help the clients to understand how the UI works in a better way. If you want to change something, you can do it (you do not have to ask my permission). But keep in mind the first sentence above. This afternoon I finish to implement the business logic then I proceed with the documentation.
